spring:
  datasource:
    hikari:
      connection-timeout: 20000
      #maximumPoolSize: 5
    ## PostgreSQL
    url: jdbc:postgresql://192.168.1.4:5432/postgres
    username: tech
    password: test
    platform: postgres
    driver-class-name: org.postgresql.Driver

    #drop n create table again, good for testing, comment this in production
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
